# Generated by Django 5.0.6 on 2025-05-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_name',
            field=models.CharField(max_length=100),
        ),
    ]
